domain: bigbang.dev

openshift: true

istio:
  enabled: true
  # values passes through to istio-controlplane chart
  values:
    profile: "openshift"
    monitoring:
      enabled: false
    networkPolicies:
      enabled: true
    values: # possible values found here https://istio.io/v1.5/docs/reference/config/installation-options (ignore 1.5, latest docs point here)
      global: # global istio operator values
        proxy: # mutating webhook injected istio sidecar proxy's values
          resources:
            requests:
              cpu: 0m # null get ignored if used here
              memory: 0Mi
            limits:
              cpu: 0m
              memory: 0Mi

istiooperator:
  enabled: true
  # values passes through to istio-operator chart

jaeger:
  enabled: true

kiali:
  enabled: true
  # values pass through to kiali chart
  values:
    istio:
      enabled: true

clusterAuditor:
  enabled: false
  # values pass through to cluster-auditor chart
  values:
    resources:
      requests:
        cpu: 400m
        memory: 2Gi
      limits:
        cpu: null
        memory: null

gatekeeper:
  enabled: true
  git:
    tag: null
    branch: "cmays-openshift-1"
  values:
    replicas: 1
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: null
          memory: null
    audit:
      resources:
        requests:
          cpu: 400m
          memory: 768Mi
        limits:
          cpu: null
          memory: null
    violations:
      allowedDockerRegistries:
        enforcementAction: dryrun
        parameters:
          repos:
            - registry1.dso.mil
            - quay.io
            - registry.redhat.io
            - image-registry.openshift-image-registry.svc
      bannedImageTags:
        enforcementAction: dryrun
      selinuxPolicy:
        enabled: false

kyverno:
  enabled: false

kyverno-policies:
  enabled: false

logging:
  enabled: true
  # values pass through to elasticsearch-kibana chart
  values:
    kibana:
      count: 1
      resources:
        requests:
          cpu: 400m
          memory: 1Gi
        limits:
          cpu: null  # nonexistent cpu limit results in faster spin up
          memory: null
    elasticsearch:
      master:
        count: 1
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: null
            memory: null
      data:
        count: 1
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: null
            memory: null

eckoperator:
  enabled: true

fluentbit:
  enabled: true

promtail:
  enabled: false

loki:
  enabled: false

tempo:
  enabled: false

# monitoring includes Prometheus, Grafana, and Alertmanager
monitoring:
  enabled: true
  values:
    alertmanager:
      enabled: false

    prometheusOperator:
      namespaces:
        releaseNamespace: true

    prometheus:

      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true

      prometheusSpec:
        thanos:
          baseImage: registry1.dso.mil/ironbank/opensource/thanos/thanos
          version: v0.29.0
        podMonitorNamespaceSelector:
          matchExpressions:
            - key: openshift.io/cluster-monitoring
              operator: NotIn
              values:
                - 'true'
            - key: openshift.io/user-monitoring
              operator: NotIn
              values:
                - 'false'
        probeNamespaceSelector:
          matchExpressions:
            - key: openshift.io/cluster-monitoring
              operator: NotIn
              values:
                - 'true'
            - key: openshift.io/user-monitoring
              operator: NotIn
              values:
                - 'false'
        serviceMonitorNamespaceSelector:
          matchExpressions:
            - key: openshift.io/cluster-monitoring
              operator: NotIn
              values:
                - 'true'
            - key: openshift.io/user-monitoring
              operator: NotIn
              values:
                - 'false'

    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false

twistlock:
  enabled: false # twistlock requires a license to work, so we're disabling it

addons:
  argocd:
    enabled: false

  authervice:
    enabled: false

  minioOperator:
    enabled: false

  minio:
    enabled: false

  gitlab:
    enabled: false

  gitlabRunner:
    enabled: false

  nexus:
    enabled: false

  sonarqube:
    enabled: false

# Deployment of HAProxy is automatically toggled depending on Monitoring SSO and Monitoring Istio Injection
  #haproxy:

  anchore:
    enabled: false

  mattermostoperator:
    enabled: false

  mattermost:
    enabled: false

  velero:
    enabled: false

  keycloak:
    enabled: false

  vault:
    enabled: false

  metricsServer:
    enabled: false
